// Run this on YOUR machine (not in a sandboxed environment) — it needs
// real internet access to reach the Overpass API, which this project's
// development sandbox doesn't have.
//
// Usage: node scripts/osm/fetchAndBuildGraph.mjs
//
// Change the BBOX below to target a different area. Format is
// [south, west, north, east] in decimal degrees.

import { writeFileSync } from "fs";
import { parseOsmToGraph } from "./parseOsmToGraph.js";

// A small area around Connaught Place, New Delhi (28.6328°N, 77.2196°E) —
// its circular/radial layout makes it a visually clear, well-known
// real-world test case. ~600m x 600m keeps node count manageable for a
// first run; widen this once the pipeline is proven out.
const BBOX = [28.6295, 77.2160, 28.6365, 77.2230];

const [south, west, north, east] = BBOX;

// Overpass QL: all ways tagged highway=* within the bounding box, plus
// the nodes they reference ("out geom" or a recursive node fetch — using
// the standard `>` recursion here to pull in every node each way uses).
const query = `
[out:json][timeout:30];
(
  way["highway"](${south},${west},${north},${east});
);
(._;>;);
out body;
`;

async function main() {
  console.log(`Querying Overpass API for bbox [${BBOX.join(", ")}]...`);

  const res = await fetch("https://overpass-api.de/api/interpreter", {
    method: "POST",
    headers: {
    "Content-Type": "text/plain",
    "Accept": "*/*",
    "User-Agent": "green-corridor-project/1.0 (student final-year project)",
    },
    body: query,
  });

  if (!res.ok) {
    throw new Error(`Overpass API responded ${res.status}: ${await res.text()}`);
  }

  const overpassJson = await res.json();
  console.log(`Received ${overpassJson.elements.length} raw OSM elements.`);

  const { graph, stats } = parseOsmToGraph(overpassJson);

  console.log("\n--- Graph build stats ---");
  console.log(`Nodes: ${stats.nodeCount}`);
  console.log(`Edges: ${stats.edgeCount}`);
  console.log(`Connected components: ${stats.componentCount} (largest: ${stats.largestComponentSize} nodes)`);
  if (stats.warnings.length > 0) {
    console.log("\nWarnings:");
    stats.warnings.forEach((w) => console.log(`  - ${w}`));
  }

  const outputPath = "algorithm/graph.real.js";
  const fileContents = `// Generated by scripts/osm/fetchAndBuildGraph.mjs
// Source: OpenStreetMap via Overpass API, bbox [${BBOX.join(", ")}]
// Generated: ${new Date().toISOString()}
// Nodes: ${stats.nodeCount}, Edges: ${stats.edgeCount}

export const graph = ${JSON.stringify(graph, null, 2)};
`;

  writeFileSync(outputPath, fileContents);
  console.log(`\nWrote ${outputPath}`);
  console.log("Review it, then rename/copy it over algorithm/graph.js when you're ready to switch.");
}

main().catch((err) => {
  console.error("Failed:", err.message);
  process.exit(1);
});